### ISSUE TITLE
Champion select's "select" text not centered properly

### ISSUE THREAD

**Issue by MythicManiac** [LeagueSandbox/LobbyClient#16]
![image](https://cloud.githubusercontent.com/assets/8225825/14656798/3ffbf5ee-0692-11e6-89a1-a1731cbc8081.png)

**Comment by molenzwiebel** [comment]
This is because of the champion icon next to it. When it is not shown (no champion selected), it is slightly off-center. I'd rather leave it like this than to move the button, which looks weird.
